export enum ResponseStatus {
    VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED",
    SUCCESS = "SUCCESS",
    NO_FROM_EMAIL = "NO_FROM_EMAIL",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USERNAME_ALREADY_TAKEN = 'USERNAME_ALREADY_TAKEN',
    ERROR = "ERROR",
    INVALID_INPUTS = "INVALID_INPUTS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
    NOT_SAVED = "NOT_SAVED",
    VERIFY_CODE_EXPIRED = "VERIFY_CODE_EXPIRED",
    INCORRECT_VERIFY_CODE = "INCORRECT_VERIFY_CODE"
}
