export enum ResponseStatus {
    VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED",
    SUCCESS = "SUCCESS",
    NO_FROM_EMAIL = "NO_FROM_EMAIL",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USERNAME_ALREADY_TAKEN = 'USERNAME_ALREADY_TAKEN',

}
